version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapeia a porta 3000 do contêiner para a porta 3000 no host
    environment:
      - NODE_ENV=production